import type { Metadata } from "next";
import "./globals.css";
// ClerkProvider commented out — replaced with JWT authentication
// import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./(auth)/provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className="font-sans">
        <Provider>
          {children}
          <Toaster position="top-center" richColors />
        </Provider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
